### PR TITLE
Fix: Same-display-name peers can't see each other (Closes #412)

### LINKED ISSUE #412: If two phones join with the same name, they can't see each other

### PR DESCRIPTION
**Pull request by darioalessandro**
Introduced a `u64` session id that the system uses to keep track of peers, now the username is not a factor.

### CODE REVIEW

File: yew-ui/src/pages/meeting.rs [hunk 1]
```diff
@@ -530,9 +530,13 @@ pub fn meeting_page(props: &MeetingPageProps) -> Html {
...
                     // User is admitted - show the meeting
                     (Some(username), MeetingStatus::Admitted { is_host, host_display_name, room_token }) => {
+                        // Use canonical email from meeting API for media connection identity (must match JWT sub).
+                        // Display name (username) is for UI only.
+                        let connection_email = (*current_user_email).clone()
+                            .unwrap_or_else(|| username.clone());
                         html! {
                             <AttendantsComponent
-                                email={username.clone()}
+                                email={connection_email}
```
Comment (darioalessandro) [inline yew-ui/src/pages/meeting.rs]: revert
